name: 'Context'

on:
  push:
  pull_request:
  pull_request_review:
  pull_request_target:
  issues:
  project:
  workflow_call:
  workflow_dispatch:


jobs:
  view-context:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        continue-on-error: true
        uses: actions/github-script@v5
        with:
          script: console.log(context)
      - name: Check secret
        shell: bash
        env: # Or as an environment variable
          SUPER_SECRET: ${{ secrets.SuperSecret }}
          USER: ${{ github.actor }}
        run: |
          echo "Secret: $SUPER_SECRET"
          echo "${USER}"
